### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kamil7732** [skjnldsv/Owncloud-FBSync#31]
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,\n\t\t\t\t\t `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`\n\t\t\t\tFROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\"1\", \"e6797323f546eaca550dfea6b7c4f328\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away","Code":0,"Trace":"#0 \/home\/admin\/web\/cloudy.com\/public_html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/admin\/web\/cloudy.com\/public_html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(836): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT `fileid`...', Array)\n#2 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/DB\/Connection.php(188): Doctrine\\DBAL\\Connection->executeQuery('SELECT `fileid`...', Array, Array, NULL)\n#3 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/Cache\/Cache.php(128): OC\\DB\\Connection->executeQuery('SELECT `fileid`...', Array)\n#4 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/Cache\/HomeCache.php(75): OC\\Files\\Cache\\Cache->get('cache\/FBfriends...')\n#5 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(926): OC\\Files\\Cache\\HomeCache->get('cache\/FBfriends...')\n#6 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(378): OC\\Files\\Storage\\Wrapper\\Encryption->getHeader('cache\/FBfriends...')\n#7 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(227): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('cache\/FBfriends...', 'w')\n#8 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(250): OC\\Files\\Storage\\Wrapper\\Encryption->file_put_contents('cache\/FBfriends...', '{\"1000011869161...')\n#9 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/View.php(1117): OC\\Files\\Storage\\Wrapper\\Wrapper->file_put_contents('cache\/FBfriends...', '{\"1000011869161...')\n#10 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Files\/View.php(671): OC\\Files\\View->basicOperation('file_put_conten...', 'FBfriends-1a84b...', Array, '{\"1000011869161...')\n#11 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Cache\/File.php(112): OC\\Files\\View->file_put_contents('FBfriends-1a84b...', '{\"1000011869161...')\n#12 \/home\/admin\/web\/cloudy.com\/public_html\/apps\/fbsync\/controller\/facebookcontroller.php(195): OC\\Cache\\File->set('FBfriends-1a84b...', '{\"1000011869161...')\n#13 \/home\/admin\/web\/cloudy.com\/public_html\/apps\/fbsync\/templates\/match.php(21): OCA\\FbSync\\Controller\\FacebookController->getfriends()\n#14 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Template\/Base.php(173): include('\/home\/admin\/web...')\n#15 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Template\/Base.php(148): OC\\Template\\Base->load('\/home\/admin\/web...', NULL)\n#16 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/legacy\/template.php(226): OC\\Template\\Base->fetchPage(NULL)\n#17 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(156): OC_Template->fetchPage()\n#18 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/AppFramework\/Http\/Dispatcher.php(112): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#19 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/AppFramework\/App.php(99): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\FbSync\\Controller\\PageController), 'match')\n#20 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('PageController', 'match', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#21 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#22 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#23 \/home\/admin\/web\/cloudy.com\/public_html\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/fbsync\/ma...')\n#24 \/home\/admin\/web\/cloudy.com\/public_html\/index.php(54): OC::handleRequest()\n#25 {main}","File":"\/home\/admin\/web\/cloudy.com\/public_html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","

Yes I see sql went gone, or is there other issue?

**Comment by kamil7732** [comment]
ok mysql xD
